In [1]:
n = 2000 # sample population
mu = 200 # sample mean
std = 30 # std dev of sample

### calculate 94% confidence interval 

In [5]:
from scipy import stats

In [24]:
np.round(stats.t.interval(alpha = 0.94, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)


C:\Users\Asus\AppData\Local\Temp\ipykernel_24196\2313344604.py:1: DeprecationWarning: Use of keyword argument 'alpha' for method 'interval' is deprecated and wil be removed in SciPy 1.11.0. Use first positional argument or keyword argument 'confidence' instead.
  np.round(stats.t.interval(alpha = 0.94, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)


array([198.74, 201.26])

### for confidence interval 96%

In [25]:
np.round(stats.t.interval(alpha = 0.96, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)

C:\Users\Asus\AppData\Local\Temp\ipykernel_24196\2863933807.py:1: DeprecationWarning: Use of keyword argument 'alpha' for method 'interval' is deprecated and wil be removed in SciPy 1.11.0. Use first positional argument or keyword argument 'confidence' instead.
  np.round(stats.t.interval(alpha = 0.96, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)


array([198.62, 201.38])

### for confidence interval 98%

In [28]:
np.round(stats.t.interval(alpha = 0.98, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)

C:\Users\Asus\AppData\Local\Temp\ipykernel_24196\2122796950.py:1: DeprecationWarning: Use of keyword argument 'alpha' for method 'interval' is deprecated and wil be removed in SciPy 1.11.0. Use first positional argument or keyword argument 'confidence' instead.
  np.round(stats.t.interval(alpha = 0.98, df=n-1, loc=mu, scale=std/np.sqrt(n)),2)


array([198.44, 201.56])